### ISSUE TITLE
extend it to IL2CPP

### ISSUE THREAD

**Issue by winux138** [Triscuit2311/Mono-Injection-Template-For-Gamehacking#1]
First I would like to thank you for this source and the videos.

I am wondering how this tempalte could be used with an IL2CPP Unity game,
o you have any tip / material ?

Once again, thanks for sharing this ressource and the videos.

**Comment by Triscuit2311** [comment]
This method is not viable for il2cpp. There are no similarities between this type of managed code injection and the native mono injection that could be used for il2cpp. Here's a good place to start with il2cpp reversing: https://github.com/djkaty/Il2CppInspector
djkaty has some other good resources on her website also.

**Comment by Triscuit2311** [comment]
I'm going to close this out, because like I mentioned this is unrelated to those methods.
